Repository season2-3team/season2-View-My-Startup-3team-FE, pull requests merged in 2024-10, with the labels that each got.

#10 [소재희] Feature/alter global
  src/Main.js
  src/components/Investment/InvestmentList.module.css
  src/components/Nav/Nav.js
  src/index.js
  src/pages/ComparisonPage.js
  src/pages/MyComparisonPage.js
  src/pages/NotFoundPage.js
  src/pages/StartupPage.js
  src/styles/global.css
  src/styles/reset.css
Labels: enhancement

#12 [서유림] Feature/investment list
  public/index.html
  src/components/App.js
  src/components/Container.js
  src/components/Container.module.css
  src/components/Investment/InvestmentDropdown.module.css
  src/components/Investment/InvestmentHeader.module.css
  src/components/Investment/InvestmentList.js
  src/components/Investment/InvestmentList.module.css
  src/components/Nav/Nav.module.css
Labels: 완료

#14 [서유림] Feature/investment modal UI
  src/components/Investment/InvestmentList.js
  src/components/Investment/InvestmentModal.js
  src/components/Investment/InvestmentModal.module.css
Labels: 완료

#15 [소재희] Feature/startup list
  src/api/StartupService.js
  src/components/Startup/StartupDropdown.js
  src/components/Startup/StartupDropdown.module.css
  src/components/Startup/StartupHeader.js
  src/components/Startup/StartupHeader.module.css
  src/components/Startup/StartupList.js
  src/components/Startup/StartupList.module.css
  src/hooks/useFetchStartups.js
  src/pages/StartupPage.js
Labels: 완료

#19 [소재희] Feature/startup list - 페이지네이션, 검색 기능 구현 및 UI 개선 작업
  public/_redirects
  public/favicon.png
  public/index.html
  src/assets/ic_clear.png
  src/assets/no-image.png
  src/components/Common/Pagination.js
  src/components/Common/Pagination.module.css
  src/components/Common/SearchInput.js
  src/components/Common/SearchInput.module.css
  src/components/Common/SortDropdown.js
  src/components/Common/sortDropdwon.module.css
  src/components/Container.module.css
  src/components/Nav/Nav.module.css
  src/components/Startup/StartupHeader.js
  src/components/Startup/StartupHeader.module.css
  src/components/Startup/StartupList.js
  src/hooks/useFetchStartups.js
  src/pages/StartupPage.js
  src/utils/formatAmount.js
Labels: 완료

#21 [소재희] Feature/startup detail link
  src/Main.js
  src/components/Startup/StartupList.js
  src/pages/StartupDetailPage.js
Labels: 완료

#17 [서유림] Feature/investment api
  package-lock.json
  package.json
  src/api/InvestmentService.js
  src/components/Investment/InvestmentDropdown.js
  src/components/Investment/InvestmentDropdown.module.css
  src/components/Investment/InvestmentHeader.js
  src/components/Investment/InvestmentList.js
  src/components/Investment/InvestmentList.module.css
  src/contexts/SortContext.js
  src/hooks/useQuery.js
  src/pages/InvestmentPage.js
  src/utils/formatAmount.js
Labels: 완료

#23 [소재희] Feature/startup list sort
  public/favicon.png
  public/images/logo5.png
  public/images/logo_codeit.png
  public/images/logo_coupang.png
  public/images/logo_daangn.png
  public/images/logo_elice.png
  public/images/logo_fastcampus.png
  public/images/logo_luxrobo.png
  public/images/logo_mathpresso.png
  public/images/logo_ncode.png
  public/images/logo_riiid.png
  public/images/logo_sparta.png
  public/images/logo_zigbang.png
  src/components/Common/SearchInput.module.css
  src/components/Startup/StartupDropdown.js
  src/components/Startup/StartupDropdown.module.css
  src/components/Startup/StartupHeader.js
  src/components/Startup/StartupList.js
Labels: 완료

#22 [서유림] Feat: 페이지네이션 추가
  src/api/InvestmentService.js
  src/components/Investment/InvestmentDropdown.js
  src/components/Investment/InvestmentDropdown.module.css
  src/components/Investment/InvestmentList.js
  src/components/Investment/InvestmentList.module.css
  src/contexts/SortContext.js
  src/hooks/useQuery.js
Labels: 완료

#18 [이도엽] Feature/selection my startup UI & API
  .gitignore
  src/assets/ic_minus.svg
  src/assets/ic_restart.svg
  src/assets/ic_x_circle_small.svg
  src/components/Selection/CompareSelectionModal.js
  src/components/Selection/CompareSelectionModal.module.css
  src/components/Selection/MySelection.js
  src/components/Selection/MySelection.module.css
  src/components/Selection/MySelectionModal.js
  src/components/Selection/MySelectionModal.module.css
  src/hooks/useFetchRecent.js
  src/pages/MyComparisonPage.js
  src/styles/variables.css
Labels: 완료

#24 [소재희] Feature/startup list enhancements
  package-lock.json
  package.json
  src/components/Common/Pagination.module.css
  src/components/Common/SearchInput.module.css
  src/components/Nav/Nav.module.css
  src/components/Startup/StartupDropdown.js
  src/components/Startup/StartupDropdown.module.css
  src/components/Startup/StartupHeader.module.css
  src/components/Startup/StartupList.js
  src/components/Startup/StartupList.module.css
  src/hooks/useFetchStartups.js
Labels: 완료

#25 feat: add StartupDetail
  src/api/InvestmentService.js
  src/api/StartupDetail.js
  src/api/StartupService.js
  src/components/StartupDetail/StartupDetail.js
  src/components/StartupDetail/StartupDetail.module.css
  src/components/StartupDetail/StartupDetailHeader.js
  src/components/StartupDetail/StartupDetailHeader.module.css
  src/components/StartupDetail/StartupDetailInfo.js
  src/components/StartupDetail/StartupDetailInfo.module.css
  src/components/StartupDetail/StartupDetailInvest.js
  src/components/StartupDetail/StartupDetailInvest.module.css
  src/pages/StartupDetailPage.js
Labels: 진행중

#26 [서유림] Feature/investment create
  src/components/Investment/InvestmentModal.js
  src/components/Investment/InvestmentModal.module.css
  src/components/StartupDetail/StartupDetailInvest.js
  src/hooks/useQuery.js
Labels: 완료

#27 [서유림] Design: 모달 최대 높이 설정 및 스크롤 추가
  src/components/Investment/InvestmentModal.module.css
Labels: 완료

#28 Fix: 나의 스타트업 선택 검색 기능
  src/components/Selection/MySelectionModal.js
  src/components/Startup/StartupList.js
  src/components/StartupDetail/StartupDetailInfo.module.css
  src/hooks/useFetchRecent.js
Labels: 완료

#30 [서유림] Feat: 투자하기 모달 유효성 검증 기능 추가
  src/components/Common/Modal.js
  src/components/Common/Modal.module.css
  src/components/Investment/InvestmentComplete.js
  src/components/Investment/InvestmentComplete.module.css
  src/components/Investment/InvestmentCreate.js
  src/components/Investment/InvestmentCreate.module.css
  src/components/Investment/InvestmentDelete.js
  src/components/Investment/InvestmentDelete.module.css
  src/components/Investment/InvestmentModal.js
  src/components/Investment/InvestmentPatch.js
  src/components/Investment/InvestmentPatch.module.css
  src/components/StartupDetail/StartupDetailInvest.js
  src/hooks/useValidate.js
Labels: 완료, 수정중

#33 [소재희] Pagination button size, border-radius, font-size configurable
  src/components/Common/Pagination.js
  src/components/Common/Pagination.module.css
  src/components/Startup/StartupList.js
Labels: 완료

#34 [서유림] Feat: 투자 현황 리스트에 투자하기 모달 연결 및 반응형 구현
  src/api/InvestmentService.js
  src/components/Common/Modal.module.css
  src/components/Investment/InvestmentComplete.js
  src/components/Investment/InvestmentComplete.module.css
  src/components/Investment/InvestmentCreate.js
  src/components/Investment/InvestmentCreate.module.css
  src/components/Investment/InvestmentDelete.js
  src/components/Investment/InvestmentDelete.module.css
  src/components/Investment/InvestmentDropdown.module.css
  src/components/Investment/InvestmentList.js
  src/components/Investment/InvestmentList.module.css
  src/components/Investment/InvestmentPatch.module.css
Labels: 완료

#36 [서유림] Feature/startup detail connect
  src/api/StartupDetail.js
  src/api/StartupDetailService.js
  src/components/StartupDetail/StartupDetail.js
  src/components/StartupDetail/StartupDetailHeader.js
  src/components/StartupDetail/StartupDetailInfo.js
  src/components/StartupDetail/StartupDetailInfo.module.css
  src/components/StartupDetail/StartupDetailInvest.js
  src/components/StartupDetail/StartupDetailInvest.module.css
Labels: 완료

#37 [소재희] Implement Not Found page with Warn component and other improvements
  package-lock.json
  package.json
  src/Main.js
  src/assets/warn.svg
  src/components/Common/Pagination.js
  src/components/Nav/Nav.js
  src/components/Startup/StartupList.js
  src/components/Startup/StartupList.module.css
  src/components/Warn.js
  src/components/Warn.module.css
  src/hooks/useFetchStartups.js
  src/pages/NotFoundPage.js
  src/utils/formatAmount.js
Labels: 완료

#32 [서지우] feat: 비교 현황 페이지 컴포넌트 폴더 추가
  src/components/ComparisonStatus/ComparisonDropdown.js
  src/components/ComparisonStatus/ComparisonDropdown.module.css
  src/components/ComparisonStatus/ComparisonHeader.js
  src/components/ComparisonStatus/ComparisonHeader.module.css
  src/components/ComparisonStatus/ComparisonList.js
  src/components/ComparisonStatus/ComparisonList.module.css
  src/pages/ComparisonPage.js
Labels: 완료

#39 [이도엽] Feature/error message
  src/components/Selection/CompareSelectionModal.js
  src/components/Selection/CompareSelectionModal.module.css
  src/components/Selection/InvestModal.js
  src/components/Selection/MySelection.js
  src/components/Selection/MySelection.module.css
  src/components/Selection/SelectionPagination.module.css
Labels: 완료

#42 [소재희] API base URL 변경
  src/api/StartupService.js
Labels: 완료

#43 [서유림] Fix: 데이터 불러오는 방식 변경 및 URL 변경
  src/api/InvestmentService.js
  src/api/StartupDetailService.js
  src/components/Investment/InvestmentComplete.js
  src/components/Investment/InvestmentCreate.js
  src/components/StartupDetail/StartupDetail.js
  src/components/StartupDetail/StartupDetail.module.css
  src/components/StartupDetail/StartupDetailDropdown.js
  src/components/StartupDetail/StartupDetailHeader.js
  src/components/StartupDetail/StartupDetailInfo.js
  src/components/StartupDetail/StartupDetailInvest.js
  src/hooks/useFetchInvestors.js
  src/hooks/useFetchStartupDetail.js
  src/pages/StartupDetailPage.js
Labels: 완료

#46 [이도엽] Feature: 기업 순위 비교하기 수정
  src/components/Selection/MySelection.js
  src/components/Selection/RankDropdown.js
  src/components/Selection/RankDropdown.module.css
  src/hooks/useFetchCancelCompare.js
  src/hooks/useFetchCancelMySelection.js
  src/hooks/useFetchCompare.js
  src/hooks/useFetchCompareResult.js
  src/hooks/useFetchMySelection.js
  src/hooks/useFetchMyStartup.js
  src/hooks/useFetchRanck.js
  src/hooks/useFetchRecent.js
Labels: 완료

#44 [서유림] Fix: 투자자 목록 드롭다운 관련 수정
  src/components/Common/Modal.module.css
  src/components/Investment/InvestmentList.js
  src/components/StartupDetail/StartupDetailDropdown.module.css
  src/components/StartupDetail/StartupDetailHeader.module.css
  src/components/StartupDetail/StartupDetailInfo.js
  src/components/StartupDetail/StartupDetailInfo.module.css
  src/components/StartupDetail/StartupDetailInvest.js
  src/components/StartupDetail/StartupDetailInvest.module.css
Labels: 완료

#49 [이도엽] Feature: responsive css
  src/components/Selection/CompareSelectionModal.module.css
  src/components/Selection/InvestModal.js
  src/components/Selection/InvestModal.module.css
  src/components/Selection/MySelection.js
  src/components/Selection/MySelection.module.css
  src/components/Selection/MySelectionModal.module.css
Labels: 완료

#51 Feat: 선택한 기업 UI 유지
  src/components/Selection/MySelection.js
Labels: 완료

#52 [소재희] conditionally apply inline styles to Pagination component
  src/components/Common/Pagination.js
  src/components/Startup/StartupList.js
Labels: 완료

#56 [소재희] update startup name style
  public/images/logo_mathpresso.png
  src/components/Startup/StartupList.js
  src/components/Startup/StartupList.module.css
Labels: 완료

#47 [서유림] Feature/fix use query
  src/components/Investment/InvestmentCreate.js
  src/components/Investment/InvestmentDelete.js
  src/components/Investment/InvestmentList.js
  src/components/Investment/InvestmentUpdate.js
  src/components/StartupDetail/StartupDetailInvest.js
  src/components/StartupDetail/StartupDetailInvest.module.css
  src/hooks/useQuery.js
  src/hooks/useValidate.js
Labels: 완료

#58 [서유림] Feature/fix invest modal
  src/components/Selection/InvestModal.js
Labels: 완료

#57 [서지우] fix: 비교 현황 페이지 정렬문제 수정
  src/components/ComparisonStatus/ComparisonHeader.module.css
  src/components/ComparisonStatus/ComparisonList.module.css
Labels: 완료

#60 [이도엽] Fix: 테이블 name 넘침
  src/components/Selection/MySelection.js
Labels: 완료

#55 [김은효] Feat: 기업상세 세부 UI 조정
  src/components/StartupDetail/StartupDetailHeader.js
  src/components/StartupDetail/StartupDetailHeader.module.css
  src/components/StartupDetail/StartupDetailInfo.js
  src/components/StartupDetail/StartupDetailInfo.module.css
  src/components/StartupDetail/StartupDetailInvest.js
  src/components/StartupDetail/StartupDetailInvest.module.css
Labels: 완료

#59 [소재희] style: adjust CSS for startup list on tablet size
  public/images/logo_codeit.png
  public/images/logo_elice.png
  public/images/logo_riiid.png
  src/components/Startup/StartupDropdown.module.css
  src/components/Startup/StartupList.js
  src/components/Startup/StartupList.module.css
Labels: 완료

#61 [서유림] Fix: 화면 깜빡임 수정
  src/components/Investment/InvestmentList.js
  src/hooks/useFetchInvestors.js
  src/hooks/useFetchStartupDetail.js
Labels: 완료

#62 [이도엽] Fix: mobile 크기일 때 모달 창 패딩 적용 및 나의 기업 선택 모달 수정
  src/components/Selection/CompareSelectionModal.module.css
  src/components/Selection/MySelection.js
  src/components/Selection/MySelection.module.css
  src/components/Selection/MySelectionModal.js
  src/components/Selection/MySelectionModal.module.css
Labels: 완료

#63 [소재희] feat: add Footer and related link pages
  public/images/logo_riiid.png
  src/Main.js
  src/components/About/About.js
  src/components/About/About.module.css
  src/components/App.js
  src/components/Common/SearchInput.module.css
  src/components/Footer/Footer.js
  src/components/Footer/Footer.module.css
  src/components/PrivacyPolicy/PrivacyPolicy.js
  src/components/PrivacyPolicy/PrivacyPolicy.module.css
  src/components/Startup/StartupDropdown.module.css
  src/components/Startup/StartupHeader.module.css
  src/components/Startup/StartupList.module.css
  src/components/Terms/Terms.js
  src/components/Terms/Terms.module.css
  src/components/Warn.module.css
  src/pages/AboutPage.js
  src/pages/PrivacyPage.js
  src/pages/TermsPage.js
Labels: 완료

#65 [이도엽] Fix: 비교 모달 창 외 클릭 시 close
  src/components/Selection/CompareSelectionModal.js
Labels: 완료

#67 [서유림] Fix: 경고 문구 제거
  src/components/Investment/InvestmentPasswordFail.js
Labels: 완료

#68 [소재희] chore: add meta tags for SNS and update about page
  public/images/view-mystartup.png
  public/index.html
  src/components/About/About.js
  src/components/About/About.module.css
Labels: 완료

#69 [김은효] Fix: 기업상세 UI 세부 조정
  src/components/StartupDetail/StartupDetailHeader.module.css
  src/components/StartupDetail/StartupDetailInfo.module.css
Labels: 완료

#70 [소재희] chore: update about page
  public/images/view-mystartup.png
  src/components/About/About.js
Labels: 완료

#71 [이도엽] Feat: 비교 페이지에서 투자 후 투자 한 기업 페이지로 이동
  src/components/Selection/InvestLink.js
  src/components/Selection/InvestModal.js
  src/components/Selection/MySelectionModal.js
Labels: 완료

#73 [김은효] Fix: 기업상세 UI 세부 조정 Info+Invest
  src/components/StartupDetail/StartupDetailInfo.module.css
  src/components/StartupDetail/StartupDetailInvest.module.css
Labels: 완료

#74 Fix: 기업상세 투자자테이블 UI 수정
  src/components/StartupDetail/StartupDetailDropdown.module.css
  src/components/StartupDetail/StartupDetailInfo.module.css
  src/components/StartupDetail/StartupDetailInvest.js
  src/components/StartupDetail/StartupDetailInvest.module.css
Labels: 완료

#75 Fix: 모달 내 이미지 위치 조정
  src/components/Selection/CompareSelectionModal.module.css
  src/components/Selection/MySelectionModal.module.css
Labels: 완료

#76 Fix: 모듈 검생창 이미지 모바일에서 조정
  src/components/Selection/CompareSelectionModal.module.css
  src/components/Selection/MySelectionModal.module.css
Labels: 완료

#77 Fix: 모듈 검색창 검색이미지 위치 조정
  src/components/Selection/CompareSelectionModal.module.css
Labels: 완료

#81 [서지우] 리드미 업데이트
  README.md
Labels: 완료

#83 [이도엽] Fix: 비교 모달 모바일 검색 이미지 조정
  src/components/Selection/CompareSelectionModal.module.css
Labels: 완료

#84 [이도엽] Feature/compare modal mobile
  src/components/Selection/CompareSelectionModal.module.css
  src/index.js
Labels: 완료

#85 [서유림] Fix: visibility button
  src/components/Investment/InvestmentCreate.js
  src/components/Investment/InvestmentDelete.js
  src/components/Investment/InvestmentPatch.js
Labels: 완료

#86 [서유림] Fix: visibility button
  src/components/Investment/InvestmentUpdate.js
Labels: 완료

#88 [서지우] 발표자료 링크 회고록에 추가
  README.md
Labels: 완료

#89 Fix: 일부 CSS 수정
  src/components/About/About.module.css
  src/components/PrivacyPolicy/PrivacyPolicy.module.css
  src/components/Terms/Terms.module.css
Labels: 완료
